config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'pages/salas'
  get 'pages/video/:id', to: 'videos#index'
  post 'upload', to: 'salas#upload'
  post 'comentarios/new', to: 'comentarios#create'
  resources :pages
  resources :comentarios
  resources :videos
  resources :usuarios
  resources :salas
  match '*path', to: 'errors#not_found', via: :all
end

app/models/video.rb
class Video < ApplicationRecord
    # Adicione os seguintes atributos
    attribute :url, :string
    attribute :title, :string
    attribute :description, :text
  end
  

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  # GET /videos or /videos.json
  def index
    @arrayMessages = []
    if params[:id]
      @video = Sala.find(params[:id])
      @video.increment!(:views)
      session[:video_id] = params[:id]
      @messages = Comentario.where(video_id: params[:id])
    else 
      @video = Sala.find(session[:id])
      @messages = Comentario.where(video_id: session[:video_id])
    end
    @messages.each do |message|
      @arrayMessages << message.attributes.slice("author", "text").values
    end
    @arrayMessages
  end

  # GET /videos/1 or /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos or /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to video_url(@video), notice: "Video was successfully created." }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1 or /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to video_url(@video), notice: "Video was successfully updated." }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1 or /videos/1.json
  def destroy
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url, notice: "Video was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.fetch(:video, {})
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_with(model: video) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
        <% video.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
  <head>
    <title>Video e Chat</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> 
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-8" id="section_video">
          <video controls>
            <source src="/videos/<%=@video.url%>" type="video/mp4"> 
            Your browser does not support the video tag.
          </video>
        </div>
        <div class="col-md-4" id="section_chat">
          <div id="chat">
            <div style="text-align: right;">
              <%= link_to "Voltar", "/pages/salas", class: "btn btn-primary back_buttom" %>
            </div>
            <div id="chat_header">
              <label>Chat</label>
              <p><span class="pin"></span><%= @video.views ? @video.views : 0 %> espectadores</p>
            </div>
            <div id="comentarios">
              <ul>
                <% if @arrayMessages %>
                  <% @arrayMessages.each do |message| %>
                    <li class="comentario"><%= message[0]%> diz: <%= message[1]%></li>
                  <% end %>
                <% end %>
              </ul>
            </div>
            <div id="new_comentario">
              <%= form_tag new_comentario_path, method: :post do %>
                <%= text_field_tag :comentario, "", :id => "comentario_content", required:true %>
                <%= text_field_tag :nome, session[:name], style: 'display:none;' %>
                <%= text_field_tag :nome, params[:id] ? params[:id] : session[:video_id], style: 'display:none;' %>
                <button id="botao_submit" type="submit"><span class="material-icons">send</span></button>               
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </body>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>