config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'pages/salas'
  get 'pages/video/:id', to: 'videos#index'
  post 'upload', to: 'salas#upload'
  post 'comentarios/new', to: 'comentarios#create'
  resources :pages
  resources :comentarios
  resources :videos
  resources :usuarios
  resources :salas
  match '*path', to: 'errors#not_found', via: :all
end

app/views/pages/_form.html.erb
<%= form_with(model: page) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<head>
  <meta charset="UTF-8">
  <title>Desafio Técnico - eRural</title>
</head>
<body>
  <div class="container">
    <div class="user-icon"></div>
    <form action="/pages/salas" method="get">
      <div class="input-group">
        <label for="name">Digite o seu nome:</label>
        <input type="text" id="name" name="name" placeholder="Digite o seu nome" required>
      </div>
      <div class="input-group">
        <input type="submit" value="Enviar">
      </div>
    </form>
  </div>
</body>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/sala.html.erb
<%= @sala_id%>

app/views/pages/salas.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <title>Vídeos</title>
  <style>
    body {
      background-color: #f5f5f5;
      font-family: sans-serif;
    }

    .container {
      width: 900px;
      margin: 0 auto;
      margin-top: 50px;
      background-color: #fff;
      padding: 20px;
      border-radius: 10px;
      box-shadow: 0 2px 5px rgba(0,0,0,0.3);
      text-align: center;
    }

    h1 {
      margin-top: 0;
    }

    .card {
      margin-top: 20px;
      background-color: #fff;
      border-radius: 10px;
      box-shadow: 0 2px 5px rgba(0,0,0,0.3);
      overflow: hidden;
      text-align: left;
      display: inline-block;
      width: calc(33.33% - 20px);
      margin-right: 20px;
    }

    .card img {
      width: 100%;
      height: 200px;
      object-fit: cover;
    }

    .card-content {
      padding: 20px;
      color: white;
      background-color: #337ab7;
      display: flex;
      min-height: 200px;
      flex-direction: column;
      justify-content: space-between;
    }
    .card-content a{
        display: flex;
        align-items: center;
        justify-content: center;
        color: #337ab7;
        background-color: white;
        height: 30px;
        border-radius: 10px;
        text-decoration: none;
    }
    .container p{
        font-size: 30px;
        font-weight: bold;
        color: #337ab7;
    }
    
  </style>
</head>
<body>
    <div style="text-align: right;">
        <%= link_to "Voltar", "/", class: "btn btn-primary back_buttom" %>
    </div>
  <div class="container">
    <p>Watch Party</p>
    <% if @salas %>
        <% @salas.each do |sala| %>
        <div class="card">
            <div class="card-content">
                <div class='title'>Titulo: <%= sala.title ? sala.title : 'Conteudo vazio' %></div>
                <div class='nome'>Transmitido por: <%= sala.nome ? sala.nome : 'Conteudo vazio' %></div>
                <div class='url'>O que esta assistindo: <%= sala.url ? sala.url : 'Conteudo vazio' %></div>
                <div class='description'>Descricao: <%= sala.description ? sala.description : 'Conteudo vazio' %></div>
                <a href = "video/<%= sala.id %>">Visualizar sala</a>
            </div>
        </div>
        <% end %>
    <% end %>
    <br>
    <div class="text-left">
        <%= link_to 'Criar Sala', new_sala_path, class: 'btn btn-primary' %>
    </div>

  </div>
</body>
</html>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>