config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'pages/salas'
  get 'pages/video/:id', to: 'videos#index'
  post 'upload', to: 'salas#upload'
  post 'comentarios/new', to: 'comentarios#create'
  resources :pages
  resources :comentarios
  resources :videos
  resources :usuarios
  resources :salas
  match '*path', to: 'errors#not_found', via: :all
end

app/models/sala.rb
class Sala < ApplicationRecord
end

app/controllers/salas_controller.rb
require 'rack/multipart'

class SalasController < ApplicationController
    def index
    end
    def new
        if session[:name]
            @user = session[:name]
        end
    end

    def upload
        uploaded_io = params[:video]
        File.open(Rails.root.join('public', 'videos', uploaded_io.original_filename), 'wb') do |file|
          file.write(uploaded_io.read)
        end
        
        @sala = Sala.new(url: params[:video].original_filename, title: params[:title], description: params[:description], nome: session[:name])
        
        respond_to do |format|
          if @sala.save
            format.html { redirect_to '/pages/salas', notice: "Video criado." }
            format.json { render :show, status: :created, location: @sala }
          else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @sala.errors, status: :unprocessable_entity }
          end
        end
      end

end

app/views/salas/new.html.erb
<div class="container">
  <h1 style="font-weight: bold; font-size: 18px;">Cadastrar nova sala</h1>
 <br>
    <%= form_tag upload_path, method: :post, multipart: true do %>
        <div class="form-group">
            <%= label_tag(:name, "Nome") %>
            <%= text_field_tag :name, @user , disabled:true%>
        </div>
        <div class="form-group">
            <%= label_tag(:title, "Titulo") %>
            <%= text_field_tag :title, "", required:true %>
        </div>
        <div class="form-group">
            <%= label_tag(:description, "Descricao") %>
            <%= text_field_tag :description, "", required: true %>
        </div>
        <div class="form-group">
            <%= label_tag(:video, "Upload do video") %>
            <%= file_field_tag :video, required: true %>
        </div>
        <%= submit_tag("Cadastrar Sala", class: "btn btn-primary") %>
    <% end %>
</div>